# render.yaml - Blueprint for deploying Open Loyalty
services:
  # 1. The main PHP/Symfony backend application
  - type: web
    name: open-loyalty-backend
    # Set this to your Git repository URL
    repo: https://github.com/your-username/your-repo
    # The build logic is now in a separate script for clarity and caching
    buildCommand: ./build.sh
    # The command to start the server after the build is complete
    startCommand: apache2-foreground
  
