services:
  oloy.segment.form_type.criterion:
      class: OpenLoyalty\Bundle\SegmentBundle\Form\Type\CriterionFormType
      arguments:
        - '@oloy.pos.repository'
        - '@broadway.uuid.generator'
      tags:
        - { name: form.type }
  oloy.segment.form_type.segment_part:
      class: OpenLoyalty\Bundle\SegmentBundle\Form\Type\SegmentPartFormType
      arguments:
        - '@broadway.uuid.generator'
      tags:
        - { name: form.type }
  oloy.segment.form_type.segment:
      class: OpenLoyalty\Bundle\SegmentBundle\Form\Type\SegmentFormType
      tags:
        - { name: form.type }
  oloy.segment.form_type.label:
      class: OpenLoyalty\Bundle\SegmentBundle\Form\Type\LabelFormType
      tags:
        - { name: form.type }
  oloy.segment.form_type.edit_segment:
      class: OpenLoyalty\Bundle\SegmentBundle\Form\Type\EditSegmentFormType
      tags:
        - { name: form.type }
  oloy.segment.param_converter:
    class: OpenLoyalty\Bundle\SegmentBundle\ParamConverter\SegmentParamConverter
    arguments: ['@oloy.segment.repository']
    tags:
      - { name: request.param_converter, priority: 2, converter: segment_converter }
  oloy.segment.customer_validator:
    class: OpenLoyalty\Bundle\SegmentBundle\Service\OloyCustomerValidator
    arguments: ['@oloy.user.read_model.repository.customer_details']
  oloy.segment.listener.segmented_customers:
    class: OpenLoyalty\Bundle\SegmentBundle\Event\Listener\SegmentedCustomersSerializationListener
    arguments:
      - '@oloy.user.read_model.repository.customer_details'
      - '@serializer'
    tags:
      - { name: jms_serializer.event_subscriber}
  oloy.segment.segment_unique:
    class: OpenLoyalty\Bundle\SegmentBundle\Service\OloySegmentValidator
    arguments: ['@oloy.segment.repository']