services:
    ol.doctrine_settings.manager:
        class: OpenLoyalty\Bundle\SettingsBundle\Service\DoctrineSettingsManager
        arguments: ['@doctrine.orm.entity_manager']
    ol.settings.manager:
        alias: ol.doctrine_settings.manager
    ol.settings.form_type.settings:
        class: OpenLoyalty\Bundle\SettingsBundle\Form\Type\SettingsFormType
        arguments: ['@ol.settings.manager', '@ol.settings.translations']
        tags:
         - { name: form.type }
    ol.settings.form_type.customers_indentification_priority:
        class: OpenLoyalty\Bundle\SettingsBundle\Form\Type\CustomersIdentificationPriority
        tags:
         - { name: form.type }
    ol.settings.frontend_translations_filesystem:
      class:     Gaufrette\Filesystem
      factory:   ['@knp_gaufrette.filesystem_map', get]
      arguments: ['frontend_translations']

    ol.settings.translations.file_based:
        class: OpenLoyalty\Bundle\SettingsBundle\Service\FileBasedTranslationsProvider
        arguments:
          - '@ol.settings.manager'
          - '@ol.settings.frontend_translations_filesystem'
          - '%fallback_frontend_translations_file%'
    ol.settings.translations:
      alias: ol.settings.translations.file_based
    ol.settings.validator.not_used_key:
        class: OpenLoyalty\Bundle\SettingsBundle\Validator\Constraints\NotUsedKeyValidator
        arguments: ['@ol.settings.translations']
        tags:
          - { name: validator.constraint_validator }
    ol.settings.validator.unique_key:
        class: OpenLoyalty\Bundle\SettingsBundle\Validator\Constraints\UniqueKeyValidator
        arguments: ['@ol.settings.translations']
        tags:
          - { name: validator.constraint_validator }