OpenLoyalty\Domain\Audit\AuditLog:
  type: entity
  repositoryClass: OpenLoyalty\Infrastructure\Audit\Persistance\Doctrine\Repository\DoctrineAuditLogRepository
  table: ol__audit
  id:
    auditLogId:
      type: audit_log_id
      column: audit_log_id
  fields:
    createdAt:
      type: datetime
    eventType:
      type: string
    entityType:
      type: string
    entityId:
      type: string
    username:
      type: string
    data:
      type: json_array