OpenLoyalty\Domain\Transaction\ReadModel\TransactionDetails:
  exlusion_policy: all
  properties:
    transactionId:
      expose: true
      inline: true
    customerId:
      expose: true
      inline: true
    posId:
      expose: true
      inline: true
  virtual_properties:
    getGrossValue:
      serialized_name: grossValue
      type: float
