services:
  oloy.transaction.command_handler:
    class: OpenLoyalty\Domain\Transaction\Command\TransactionCommandHandler
    arguments:
      - '@oloy.transaction.repository'
    lazy: true
    tags:
      - { name: command_handler }
  oloy.transaction.repository:
    class: OpenLoyalty\Domain\Transaction\TransactionRepository
    arguments:
      - '@broadway.event_store'
      - '@broadway.event_handling.event_bus'
      - ['@broadway.metadata_enriching_event_stream_decorator']
  oloy.transaction.read_model.repository.transaction_details:
    class: 'Broadway\ReadModel\ReadModel'
    factory: ['@oloy.user.read_model.repository_factory', create]
    arguments:
      - 'oloy.transactions_details'
      - 'OpenLoyalty\Domain\Transaction\ReadModel\TransactionDetails'
      - 'OpenLoyalty\Domain\Repository\Transaction\TransactionDetailsElasticsearchRepository'
  oloy.transaction.read_model.projector.transaction_details:
    class: 'OpenLoyalty\Domain\Transaction\ReadModel\TransactionDetailsProjector'
    tags:
      - { name: broadway.domain.event_listener }
    arguments:
      - '@oloy.transaction.read_model.repository.transaction_details'
      - '@oloy.pos.repository'
  oloy.transaction.listener.assing_customer_to_transaction:
    class: OpenLoyalty\Domain\Transaction\Event\Listener\AssignCustomerToTransactionListener
    arguments:
      - '@oloy.transaction.customer_id_provider'
      - '@broadway.command_handling.command_bus'
      - '@broadway.event_dispatcher'
      - '@oloy.transaction.read_model.repository.transaction_details'
      - '@oloy.transaction.oloy_customer_transactions_summary_provider'
    lazy: true
    tags:
      - { name: broadway.domain.event_listener }
