services:
  oloy.campaign.form_type.campaign:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\CampaignFormType
    tags:
      - { name: form.type }
  oloy.campaign.form_type.edit_campaign:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\EditCampaignFormType
    tags:
      - { name: form.type }
  oloy.campaign.form_type.campaign_activity:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\CampaignActivityFormType
    tags:
      - { name: form.type }
  oloy.campaign.form_type.campaign_visibility:
    class: OpenLoyalty\Bundle\CampaignBundle\Form\Type\CampaignVisibilityFormType
    tags:
      - { name: form.type }
  oloy.campaign.param_converter:
    class: OpenLoyalty\Bundle\CampaignBundle\ParamConverter\CampaignParamConverter
    arguments: ['@oloy.campaign.repository']
    tags:
      - { name: request.param_converter, priority: 2, converter: campaign_converter }
  oloy.campaign.campaign_provider:
    class: OpenLoyalty\Bundle\CampaignBundle\Service\CampaignProvider
    arguments:
      - '@oloy.segment.read_model.repository.segmented_customers'
      - '@oloy.user.read_model.repository.customers_belonging_to_one_level'
      - '@oloy.campaign.read_model.repository.coupon_usage'
      - '@oloy.campaign.campaign_validator'
      - '@oloy.campaign.read_model.repository.campaign_usage'

  oloy.campaign.campaign_validator:
    class: OpenLoyalty\Bundle\CampaignBundle\Service\CampaignValidator
    arguments:
      - '@oloy.campaign.read_model.repository.coupon_usage'
      - '@oloy.points.account.repository.account_details'
  oloy.campaign.serialization_listener:
    class: OpenLoyalty\Bundle\CampaignBundle\Event\Listener\CampaignSerializationListener
    arguments:
      - '@oloy.campaign.campaign_validator'
      - '@oloy.segment.repository'
      - '@oloy.level.repository'
      - '@oloy.campaign.read_model.repository.coupon_usage'
      - '@oloy.campaign.campaign_provider'
      - '@oloy.campaign.read_model.repository.campaign_usage'
      - '@oloy.customer_status_provider'
      - '@router'
    tags:
      - { name: jms_serializer.event_subscriber }

  oloy.campaign.photos_filesystem:
    class:     Gaufrette\Filesystem
    factory:   ['@knp_gaufrette.filesystem_map', get]
    arguments: ['campaign_photos']

  oloy.campaign.photo_uploader:
    class: OpenLoyalty\Bundle\CampaignBundle\Service\CampaignPhotoUploader
    arguments: ["@oloy.campaign.photos_filesystem"]

  oloy.campaign.validator.image:
    class: OpenLoyalty\Bundle\CampaignBundle\Validator\Constraints\ImageValidator
    arguments:
      - '%oloy.campaign.photos_min_width%'
      - '%oloy.campaign.photos_min_height%'
    tags:
      - { name: validator.constraint_validator }