services:
  oloy.level.command_handler:
    class: OpenLoyalty\Domain\Level\Command\LevelCommandHandler
    arguments:
      - '@oloy.level.repository'
      - '@oloy.special_reward.repository'
    lazy: true
    tags:
      - { name: command_handler }
  oloy.level.repository:
    class: OpenLoyalty\Infrastructure\Level\Persistance\Doctrine\Repository\DoctrineLevelRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - 'OpenLoyalty\Domain\Level\Level'

  oloy.special_reward.repository:
    class: OpenLoyalty\Infrastructure\Level\Persistance\Doctrine\Repository\DoctrineSpecialRewardRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - 'OpenLoyalty\Domain\Level\SpecialReward'
