OpenLoyalty\Domain\EarningRule\EarningRule:
  exlusion_policy: ALL
  discriminator:
    field_name: type
    map:
      points: OpenLoyalty\Domain\EarningRule\PointsEarningRule
      event: OpenLoyalty\Domain\EarningRule\EventEarningRule
      custom_event: OpenLoyalty\Domain\EarningRule\CustomEventEarningRule
      product_purchase: OpenLoyalty\Domain\EarningRule\ProductPurchaseEarningRule
      multiply_for_product: OpenLoyalty\Domain\EarningRule\MultiplyPointsForProductEarningRule
      referral: OpenLoyalty\Domain\EarningRule\ReferralEarningRule
  properties:
    earningRuleId:
      expose: true
      inline: true
    levels:
      exclude: true
    segments:
      exclude: true
  virtual_properties:
      getFlatLevels:
          serialized_name: levels
          type: array
      getFlatSegments:
          serialized_name: segments
          type: array
