services:
  oloy.email.repository:
    class: OpenLoyalty\Infrastructure\Email\Persistance\Doctrine\Repository\DoctrineEmailRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - 'OpenLoyalty\Domain\Email\Email'

  oloy.email.command_handler:
    class: OpenLoyalty\Domain\Email\Command\EmailCommandHandler
    arguments:
      - '@oloy.email.repository'
      - '@broadway.event_dispatcher'
      - { from_name: '%mailer_from_name%', from_address: '%mailer_from_address%' }
    lazy: true
    tags:
      - { name: command_handler }

  oloy.email.read_model.repository:
    class: OpenLoyalty\Infrastructure\Email\ReadModel\Doctrine\Repository\DoctrineEmailRepository
    arguments:
      - '@doctrine.dbal.default_connection'
