parameters:
  oloy.emails:
      - { template: 'OpenLoyaltyUserBundle:email:registration.html.twig', subject: 'Account created', variables: ['url'] }
      - { template: 'OpenLoyaltyUserBundle:email:registration_with_temporary_password.html.twig', subject: 'Account created', variables: ['program_name', 'email', 'loyalty_card_number', 'phone', 'password', 'customer_panel_url'] }
      - { template: 'OpenLoyaltyUserBundle:email:password_reset.html.twig', subject: 'Password reset requested', variables: ['program_name', 'url_reset_password'] }
      - { template: 'OpenLoyaltyUserBundle:email:customer_reward_bought.html.twig', subject: '%s - new reward', variables: ['program_name', 'reward_name', 'reward_code', 'reward_instructions', 'ecommerce_address'] }
      - { template: 'OpenLoyaltyUserBundle:email:new_points.html.twig', subject: '%s - new points', variables: ['program_name', 'added_points_amount', 'active_points_amount', 'ecommerce_address'] }
      - { template: 'OpenLoyaltyUserBundle:email:new_level.html.twig', subject: '%s - new level', variables: ['program_name', 'level_name', 'level_discount', 'ecommerce_address'] }

services:
  # Mock services to replace Broadway-based repositories
  oloy.user.read_model.repository.customer_details:
    class: OpenLoyalty\Bundle\UserBundle\Service\MockCustomerDetailsRepository
    public: true
  oloy.user.read_model.repository.invitation_details:
    class: OpenLoyalty\Bundle\UserBundle\Service\MockInvitationDetailsRepository
    public: true
  oloy.user.read_model.repository.seller_details:
    class: OpenLoyalty\Bundle\UserBundle\Service\MockSellerDetailsRepository
    public: true
  oloy.points.account.repository.account_details:
    class: OpenLoyalty\Domain\Repository\Account\AccountDetailsRepositoryImpl
    public: true
  oloy.points.account.repository.points_transfer_details:
    class: OpenLoyalty\Domain\Account\ReadModel\PointsTransferDetailsRepositoryImpl
    public: true
  oloy.user.read_model.repository.customers_belonging_to_one_level:
    class: OpenLoyalty\Bundle\UserBundle\Service\MockCustomerDetailsRepository
    public: true
  oloy.transaction.read_model.repository.transaction_details:
    class: OpenLoyalty\Bundle\UserBundle\Service\MockCustomerDetailsRepository
    public: true
  oloy.segment.read_model.repository.segmented_customers:
    class: OpenLoyalty\Bundle\UserBundle\Service\MockCustomerDetailsRepository
    public: true
  oloy.campaign.read_model.repository.coupon_usage:
    class: OpenLoyalty\Bundle\UserBundle\Service\MockCouponUsageRepository
    public: true

  # Alias for autowiring
  OpenLoyalty\Domain\Campaign\ReadModel\CouponUsageRepository: '@oloy.campaign.read_model.repository.coupon_usage'
  oloy.campaign.read_model.repository.campaign_usage:
    class: OpenLoyalty\Bundle\UserBundle\Service\MockCampaignUsageRepository
    public: true

  # Alias for autowiring
  OpenLoyalty\Domain\Campaign\ReadModel\CampaignUsageRepository: '@oloy.campaign.read_model.repository.campaign_usage'
  
  # Alias for Broadway RepositoryInterface
  Broadway\ReadModel\RepositoryInterface: '@oloy.user.read_model.repository.customer_details'
  
  # Alias for PointsTransferDetailsRepository
  OpenLoyalty\Domain\Account\ReadModel\PointsTransferDetailsRepository: '@oloy.points.account.repository.points_transfer_details'
  
  # Alias for SellerDetailsRepository
  OpenLoyalty\Domain\Seller\ReadModel\SellerDetailsRepository: '@oloy.user.read_model.repository.seller_details'
  
  # Alias for AccountDetailsRepository
  OpenLoyalty\Domain\Account\ReadModel\AccountDetailsRepository: '@oloy.points.account.repository.account_details'
  
  # Alias for CustomerDetailsRepository
  OpenLoyalty\Domain\Customer\ReadModel\CustomerDetailsRepository: '@oloy.user.read_model.repository.customer_details'
  
  # Alias for TransactionDetailsRepository
  OpenLoyalty\Domain\Transaction\ReadModel\TransactionDetailsRepository: '@oloy.transaction.read_model.repository.transaction_details'
  
  # Alias for InvitationDetailsRepository
  OpenLoyalty\Domain\Customer\ReadModel\InvitationDetailsRepository: '@oloy.user.read_model.repository.invitation_details'
  
  broadway.uuid.generator:
    class: stdClass
    public: true
  oloy.user.read_model.repository_factory:
    class: OpenLoyalty\Bundle\UserBundle\Service\RepositoryFactory
    public: true

  oloy.user.all_users_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\UserProvider
    arguments:
      - '@doctrine.orm.entity_manager'
  oloy.user.admin_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\AdminProvider
    arguments:
      - '@doctrine.orm.entity_manager'
  oloy.user.seller_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\SellerProvider
    arguments:
      - '@doctrine.orm.entity_manager'
  oloy.user.customer_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\CustomerProvider
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@oloy.user.read_model.repository.customer_details'
  oloy.user.user_manager:
    class: OpenLoyalty\Bundle\UserBundle\Service\UserManager
    arguments:
      - '@security.password_encoder'
      - '@doctrine.orm.entity_manager'
      - '@oloy.user.password_generator'
      - '@oloy.user.email_provider'
      - '@oloy.user.read_model.repository.customer_details'
  # oloy.user.event.authentication_success_listener:
  #   class: OpenLoyalty\Bundle\UserBundle\EventListener\AuthenticationListener
  #   arguments: ['@oloy.user.user_manager', '@broadway.event_dispatcher']
  #   tags:
  #     - { name: kernel.event_listener, event: user.login_success, method: onAuthenticationSuccessResponse }
  #     - { name: kernel.event_listener, event: user.login_failure, method: onAuthenticationFailureResponse }
  oloy.user.form_type.change_password:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\ChangePasswordFormType
    tags:
      - { name: form.type }
  oloy.user.form_type.admin:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\AdminFormType
    tags:
      - { name: form.type }
  oloy.user.form_type.password_reset:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\PasswordResetFormType
    tags:
      - { name: form.type }
  oloy.user.form_type.customer_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\CustomerRegistrationFormType
    arguments: ['@oloy.level.repository', '@oloy.pos.repository']
    tags:
      - { name: form.type }
  oloy.user.form_type.customer_self_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\CustomerSelfRegistrationFormType
    tags:
      - { name: form.type }
  oloy.user.form_type.customer_edit:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\CustomerEditFormType
    tags:
      - { name: form.type }

  oloy.user.form_type.seller_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Type\SellerRegistrationFormType
    arguments:
      - '@oloy.pos.repository'
    tags:
      - { name: form.type }
  oloy.user.form_handler.customer_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\CustomerRegistrationFormHandler
    arguments:
      - '@oloy.user.user_manager'
      - '@doctrine.orm.entity_manager'
      - '@oloy.user.customer.unique_validator'
  oloy.user.form_handler.invitation:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\InvitationFormHandler
    arguments:
      - '@oloy.user.read_model.repository.invitation_details'
      - '@oloy.user.read_model.repository.customer_details'
      - '@oloy.user.email_provider'
  oloy.user.form_handler.seller_registration:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\SellerRegistrationFormHandler
    arguments:
      - '@oloy.user.user_manager'
      - '@doctrine.orm.entity_manager'
  oloy.user.form_handler.customer_edit:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\CustomerEditFormHandler
    arguments:
      - '@oloy.user.user_manager'
      - '@doctrine.orm.entity_manager'
      - '@oloy.user.customer.unique_validator'
  oloy.user.form_handler.seller_edit:
    class: OpenLoyalty\Bundle\UserBundle\Form\Handler\SellerEditFormHandler
    arguments:
      - '@oloy.user.user_manager'
      - '@doctrine.orm.entity_manager'
  oloy.user.random_password_generator:
    class: OpenLoyalty\Bundle\UserBundle\Service\RandomStringPasswordGenerator
  oloy.user.password_generator:
    alias: 'oloy.user.random_password_generator'
  oloy.user.email_provider:
    class: OpenLoyalty\Bundle\UserBundle\Service\EmailProvider
    arguments:
      - '@oloy.email.message_factory'
      - '@oloy.mailer'
      - {from_name: '%mailer_from_name%', from_address: '%mailer_from_address%', password_reset_url: '%frontend_password_reset_url%', loyalty_program_name: '%loyalty_program_name%', ecommerce_address: '%ecommerce_address%', customer_panel_url: '%frontend_customer_panel_url%'}

  oloy.user.es_param_manager:
    class: OpenLoyalty\Bundle\UserBundle\Service\EsParamManager
  oloy.user.param_manager:
    alias: 'oloy.user.es_param_manager'

  oloy.user.listener.customer_serialization_listener:
    class: OpenLoyalty\Bundle\UserBundle\EventListener\CustomerSerializationListener
    arguments: ['@oloy.level.repository', '@ol.settings.manager', '@oloy.pos.repository']
    tags:
      - { name: jms_serializer.event_subscriber }

  oloy.user.level_id_provider:
    class: 'OpenLoyalty\Bundle\UserBundle\Service\OloyLevelIdProvider'
    arguments:
      - '@oloy.level.repository'


  oloy.user.settings_based_tier_assign_type_provider:
    class: 'OpenLoyalty\Bundle\UserBundle\Service\SettingsBasedTierAssignTypeProvider'
    arguments:
      - '@ol.settings.manager'

  oloy.user.settings_based_exclude_delivery_costs_provider:
    class: 'OpenLoyalty\Bundle\UserBundle\Service\SettingsBasedExcludeDeliveryCostsProvider'
    arguments:
      - '@ol.settings.manager'

  oloy.user.tier_assign_type_provider:
    alias: oloy.user.settings_based_tier_assign_type_provider
  oloy.user.exclude_delivery_costs_provider:
    alias: oloy.user.settings_based_exclude_delivery_costs_provider

  oloy.user.random_number_token_generator:
    class: OpenLoyalty\Bundle\UserBundle\Service\RandomNumberTokenGenerator

  oloy.user.token_generator:
    alias: oloy.user.random_number_token_generator

  oloy.customer_status_provider:
    class: OpenLoyalty\Bundle\UserBundle\Status\CustomerStatusProvider
    arguments:
      - '@oloy.points.account.repository.account_details'
      - '@oloy.level.repository'
      - '@oloy.user.read_model.repository.customer_details'
      - '@oloy.user.tier_assign_type_provider'
      - '@oloy.user.exclude_delivery_costs_provider'
      - '@ol.settings.manager'
  oloy.user.param_converter.customer:
    class: OpenLoyalty\Bundle\UserBundle\ParamConverter\CustomerDetailsParamConverter
    arguments: ['@oloy.user.read_model.repository.customer_details']
    tags:
      - { name: request.param_converter, priority: -2, converter: customer_details_converter }
  oloy.user.param_converter.seller:
    class: OpenLoyalty\Bundle\UserBundle\ParamConverter\SellerDetailsParamConverter
    arguments: ['@oloy.user.read_model.repository.seller_details']
    tags:
      - { name: request.param_converter, priority: -2, converter: seller_details_converter }

  oloy.user.doctrine_repository.admin:
    class: OpenLoyalty\Bundle\UserBundle\Entity\Repository\DoctrineAdminRepository
    factory:
      - '@doctrine.orm.default_entity_manager'
      - getRepository
    arguments:
      - 'OpenLoyalty\Bundle\UserBundle\Entity\Admin'

  oloy.user.repository.admin:
    alias: oloy.user.doctrine_repository.admin

  oloy.user.admin.command_handler:
      class: OpenLoyalty\Bundle\UserBundle\CQRS\Handler\AdminHandler
      arguments:
        - '@oloy.user.user_manager'
        - '@oloy.user.repository.admin'
      lazy: true
      tags:
        - { name: command_handler }

  oloy.user.listener.customer_level_changed:
      class: OpenLoyalty\Bundle\UserBundle\EventListener\CustomerLevelChangedListener
      arguments:
        - '@oloy.user.email_provider'
        - '@oloy.level.repository'
        - '@oloy.user.read_model.repository.customer_details'
      tags:
        - { name: kernel.event_listener, event: oloy.customer.level_changed, method: sendEmail }
  oloy.user.listener.user_registered_with_invitation_token:
      class: OpenLoyalty\Bundle\UserBundle\EventListener\UserRegisteredWithInvitationTokenListener
      arguments:
        - '@oloy.user.read_model.repository.invitation_details'
      tags:
        - { name: kernel.event_listener, event: user.invitation.user_registered_with_invitation_token, method: handle }

  # Custom JWT Authentication Services
  oloy.user.jwt_authenticator:
    class: OpenLoyalty\Bundle\UserBundle\Security\Authenticator\JWTAuthenticator
    arguments: ['%jwt_secret%', '%jwt_algorithm%']

  oloy.user.authentication_success_handler:
    class: OpenLoyalty\Bundle\UserBundle\Security\Handler\AuthenticationSuccessHandler
    arguments: ['%jwt_secret%', '%jwt_algorithm%', '%jwt_token_ttl%', '@oloy.user.user_manager']

  oloy.user.authentication_failure_handler:
    class: OpenLoyalty\Bundle\UserBundle\Security\Handler\AuthenticationFailureHandler

  OpenLoyalty\Bundle\UserBundle\Command\CreateProjectionIndexCommand:
    tags:
      - { name: console.command }