services:
  oloy.user.voters.customer:
    class: OpenLoyalty\Bundle\UserBundle\Security\Voter\CustomerVoter
    arguments:
      - '@oloy.user.read_model.repository.seller_details'
    tags:
      - { name: security.voter }
  oloy.user.voters.user:
    class: OpenLoyalty\Bundle\UserBundle\Security\Voter\UserVoter
    tags:
      - { name: security.voter }
  oloy.user.voters.seller:
    class: OpenLoyalty\Bundle\UserBundle\Security\Voter\SellerVoter
    tags:
      - { name: security.voter }
  oloy.user.voters.search_customer:
    class: OpenLoyalty\Bundle\UserBundle\Security\Voter\CustomerSearchVoter
    tags:
      - { name: security.voter }
  oloy.user.voters.admin:
    class: OpenLoyalty\Bundle\UserBundle\Security\Voter\AdminVoter
    tags:
      - { name: security.voter }
  oloy.user.voters.invitation:
    class: OpenLoyalty\Bundle\UserBundle\Security\Voter\InvitationVoter
    tags:
      - { name: security.voter }